repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --ignore=W503
          - --inline-quotes=double
        additional_dependencies:
          - flake8-broken-line
          - flake8-eradicate
          - flake8-print
          - flake8-quotes
          - flake8-simplify
          - flake8-annotations-complexity
          - flake8-multiline-containers
          - flake8-mock
